### ISSUE TITLE
set up Kanban board

### ISSUE THREAD

**Issue by GraceHtet** [GraceHtet/AnimePg_JSCapstone#21]
[github Project](https://github.com/GraceHtet/AnimePg_JSCapstone/projects/1
)
There are only two people in our team.

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @GraceHtet and @joshualyngdoh,

✔️ Tasks are complete and evenly assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
